- name: Change root password
  hosts: "{{ target_hosts }}"
  vars_files:
    - vars/external-vars.yml
  become: yes
  tasks:

    - name: Change password
      user:
        name: root
        update_password: always
        password: "{{ new_sudo_pass|password_hash('sha512') }}"